CLIENT_LIB_PATH = "../cpp_libs/Client_Lib.so"
SERVER_LIB_PATH = "../cpp_libs/Server_Lib.so"
TEST_DOCUMENT_PATH = "../../test/test4.txt"
TEST_DECRYPTED_DOC_PATH = "../../test/test.bin"
TEST_RECOVERED_DOC_PATH = "../../test/recovered.txt"